# Setup
title:        zaidhuda
tagline:      accept the change or forget the chance
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Zaid Huda
  url:        https://hudadiaz.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
