# Setup
title:        zaidhuda
tagline:      accept the change or forget the chance
description:  Zaid Huda's personal blog.
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Zaid Huda
  url:        https://zaidhuda.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
