# Setup
title:          Zaid Huda
tagline:        that's the name
description:    A dreamless selfless narcissist music loving programmer that has trouble programming and socializing.
baseurl:        ""
paginate:       5
paginate_path:  "/blog/page:num/"
_url:            https://www.zaidhuda.com

# About/contact
author:
  name:       Zaid Huda
  url:        https://www.zaidhuda.com

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
